const Orders = [
  {
    reference: "#AD452",
    reason: "Purchase Product!!",
    seller: "Admin",
    productName: "James Morris",
    createDate: "08 Dec, 2021",
    status: "Adjust Stock",
    statusClass: "success",
    qty: "5",
    qtyClass: "success",
    isSelected:false
  },
  {
    reference: "#AD453",
    reason: "Return to Company!!!",
    seller: "Admin",
    productName: "David Nichols",
    createDate: "24 Oct, 2021",
    status: "Adjust Stock",
    statusClass: "danger",
    qty: "-3",
    qtyClass: "danger",
    isSelected:false
  },
  {
    reference: "#INV454",
    reason: "etc!",
    seller: "Admin",
    productName: "Nancy Martino",
    createDate: "17 Oct, 2021",
    dueDate: "23 Oct, 2021",
    status: "Sale",
    statusClass: "warning",
    qty: "5",
    qtyClass: "warning",
    isSelected:false
  },
  {
    reference: "#AD452",
    reason: "Purchase Product!!",
    seller: "Admin",
    productName: "James Morris",
    createDate: "08 Dec, 2021",
    status: "Adjust Stock",
    statusClass: "success",
    qty: "5",
    qtyClass: "success",
    isSelected:false
  },
  {
    reference: "#AD453",
    reason: "Return to Company!!!",
    seller: "Admin",
    productName: "David Nichols",
    createDate: "24 Oct, 2021",
    status: "Adjust Stock",
    statusClass: "danger",
    qty: "-3",
    qtyClass: "danger",
    isSelected:false
  },
  {
    reference: "#INV454",
    reason: "etc!",
    seller: "Admin",
    productName: "Nancy Martino",
    createDate: "17 Oct, 2021",
    dueDate: "23 Oct, 2021",
    status: "Sale",
    statusClass: "warning",
    qty: "5",
    qtyClass: "warning",
    isSelected:false
  },
  {
    reference: "#AD452",
    reason: "Purchase Product!!",
    seller: "Admin",
    productName: "James Morris",
    createDate: "08 Dec, 2021",
    status: "Adjust Stock",
    statusClass: "success",
    qty: "5",
    qtyClass: "success",
    isSelected:false
  },
  {
    reference: "#AD453",
    reason: "Return to Company!!!",
    seller: "Admin",
    productName: "David Nichols",
    createDate: "24 Oct, 2021",
    status: "Adjust Stock",
    statusClass: "danger",
    qty: "-3",
    qtyClass: "danger",
    isSelected:false
  },
  {
    reference: "#INV454",
    reason: "etc!",
    seller: "Admin",
    productName: "Nancy Martino",
    createDate: "17 Oct, 2021",
    dueDate: "23 Oct, 2021",
    status: "Sale",
    statusClass: "warning",
    qty: "5",
    qtyClass: "warning",
    isSelected:false
  },
  {
    reference: "#AD452",
    reason: "Purchase Product!!",
    seller: "Admin",
    productName: "James Morris",
    createDate: "08 Dec, 2021",
    status: "Adjust Stock",
    statusClass: "success",
    qty: "5",
    qtyClass: "success",
    isSelected:false
  },
  {
    reference: "#AD453",
    reason: "Return to Company!!!",
    seller: "Admin",
    productName: "David Nichols",
    createDate: "24 Oct, 2021",
    status: "Adjust Stock",
    statusClass: "danger",
    qty: "-3",
    qtyClass: "danger",
    isSelected:false
  },
  {
    reference: "#INV454",
    reason: "etc!",
    seller: "Admin",
    productName: "Nancy Martino",
    createDate: "17 Oct, 2021",
    dueDate: "23 Oct, 2021",
    status: "Sale",
    statusClass: "warning",
    qty: "5",
    qtyClass: "warning",
    isSelected:false
  },
  
]

export { Orders };
