const Leads = [
  {
    id: "001",
    item_name: "Force Medicines",
    brand: "Los Angeles, USA",
    stock_avai: ["Partner"],
    priority: "High",
    priorityClass: "success",
  },
  {
    id: "002",
    item_name: "iTest Factory",
    brand: "Phoenix, USA",
    stock_avai: ["Partner"],
    priority: "Low",
    priorityClass: "danger",
  },
  {
    id: "003",
    item_name: "Syntyce Solutions",
    brand: "London, UK",
    stock_avai: ["Lead", "Partner"],
    priority: "Medium",
    priorityClass: "warning",
  },
  {
    id: "004",
    item_name: "Micro Design",
    brand: "Damascus, Syria",
    stock_avai: ["Exiting", "Lead", "Partner"],
    priority: "High",
    priorityClass: "success",
  },
  {
    id: "005",
    item_name: "Nesta Technologies",
    brand: "Bogota, Colombia",
    stock_avai: ["Long-term", "Lead"],
    priority: "Medium",
    priorityClass: "warning",
  },
  {
    id: "006",
    item_name: "Zoetic Fashion",
    brand: "Windhoek, Namibia",
    stock_avai: ["Exiting"],
    priority: "High",
    priorityClass: "success",
  },
  {
    id: "007",
    item_name: "Moetic Fashion",
    brand: "Berlin, Germany",
    stock_avai: ["Long-term", "Lead"],
    priority: "Low",
    priorityClass: "danger",
  },
  {
    id: "008",
    item_name: "Syntyce Solutions",
    brand: "Brasilia, Brazil",
    stock_avai: ["Lead"],
    priority: "Medium",
    priorityClass: "warning",
  },
  {
    id: "009",
    item_name: "Digitech Galaxy",
    brand: "Windhoek, Namibia",
    stock_avai: ["Lead", "Partner"],
    priority: "High",
    priorityClass: "success",
  },
  {
    id: "010",
    item_name: "Micro Design",
    brand: "London, UK",
    stock_avai: ["Lead"],
    priority: "Low",
    priorityClass: "danger",
  },
  {
    id: "011",
    item_name: "Syntyce Solutions",
    brand: "London, UK",
    stock_avai: ["Lead", "Partner"],
    priority: "Medium",
    priorityClass: "warning",
  },
  
];


export { Leads };
